<?php

return [
    'AR' => 'Argentina,ARG,4,D',
    'AU' => 'Australia,AUS,37,C',
    'BE' => 'Belgium,BEL,5,G',
    'BR' => 'Brazil,BRA,2,E',
    'CH' => 'Switzerland,SWI,8,E',
    'CO' => 'Colombia,COL,13,H',
    'CR' => 'Costa Rica,COS,26,E',
    'DK' => 'Denmark,DEN,12,C',
    'DE' => 'Germany,GER,1,F',
    'EG' => 'Egypt,EGY,44,A',
    'EN' => 'England,ENG,16,G',
    'ES' => 'Spain,SPA,6,B',
    'FR' => 'France,FRA,9,C',
    'HR' => 'Croatia,HRV,15,D',
    'IR' => 'Iran,IRN,33,B',
    'IS' => 'Iceland,ICE,18,D',
    'JP' => 'Japan,JPN,55,H',
    'KR' => 'South Korea,KOR,59,F',
    'MA' => 'Morocco,MOR,42,B',
    'ME' => 'Mexico,MEX,17,F',
    'NG' => 'Nigeria,NIG,52,D',
    'PA' => 'Panama,PAN,53,G',
    'PE' => 'Peru,PER,11,C',
    'PL' => 'Poland,POL,6,H',
    'PR' => 'Portugal,POR,3,B',
    'RU' => 'Russia,RUS,63,A',
    'SA' => 'Saudi Arabia,SAU,69,A',
    'SN' => 'Senegal,SEN,27,H',
    'SR' => 'Serbia,SRB,34,E',
    'SE' => 'Sweden,SWE,19,F',
    'TN' => 'Tunisia,TUN,23,G',
    'UY' => 'Uruguay,URY,22,A',
];