<?php

return [
    'ARG' => 'Argentina,,4,D',
    'AUS' => 'Australia,,37,C',
    'BEL' => 'Belgium,,5,G',
    'BRA' => 'Brazil,,2,E',
    'CHE' => 'Switzerland,SWI,8,E',
    'COL' => 'Colombia,,13,H',
    'CRI' => 'Costa Rica,COS,26,E',
    'DNK' => 'Denmark,DEN,12,C',
    'DEU' => 'Germany,GER,1,F',
    'EGY' => 'Egypt,,44,A',
    'ESP' => 'Spain,SPA,6,B',
    'FRA' => 'France,,9,C',
    'GBR' => 'England,ENG,16,G',
    'HRV' => 'Croatia,HRV,15,D',
    'IRN' => 'Iran,,33,B',
    'ISL' => 'Iceland,ICE,18,D',
    'JPN' => 'Japan,,55,H',
    'KOR' => 'South Korea,,59,F',
    'MAR' => 'Morocco,MOR,42,B',
    'MEX' => 'Mexico,,17,F',
    'NGA' => 'Nigeria,NIG,52,D',
    'PAN' => 'Panama,,53,G',
    'PER' => 'Peru,,11,C',
    'POL' => 'Poland,,6,H',
    'PRT' => 'Portugal,POR,3,B',
    'RUS' => 'Russia,,63,A',
    'SAU' => 'Saudi Arabia,,69,A',
    'SEN' => 'Senegal,,27,H',
    'SRB' => 'Serbia,,34,E',
    'SWE' => 'Sweden,,19,F',
    'TUN' => 'Tunisia,,23,G',
    'URY' => 'Uruguay,,22,A',
];